export const enum AudioFieldsAlbum {
    title = "title",
    description = "description",
    artist = "artist",
    genre = "genre",
    theme = "theme",
    mood = "mood",
    style = "style",
    type = "type",
    albumlabel = "albumlabel",
    rating = "rating",
    votes = "votes",
    userrating = "userrating",
    year = "year",
    musicbrainzalbumid = "musicbrainzalbumid",
    musicbrainzalbumartistid = "musicbrainzalbumartistid",
    fanart = "fanart",
    thumbnail = "thumbnail",
    playcount = "playcount",
    artistid = "artistid",
    displayartist = "displayartist",
    compilation = "compilation",
    releasetype = "releasetype",
    dateadded = "dateadded",
    sortartist = "sortartist",
    musicbrainzreleasegroupid = "musicbrainzreleasegroupid",
    songgenres = "songgenres",
    art = "art",
    lastplayed = "lastplayed",
    sourceid = "sourceid",
    isboxset = "isboxset",
    totaldiscs = "totaldiscs",
    releasedate = "releasedate",
    originaldate = "originaldate",
    albumstatus = "albumstatus",
    datemodified = "datemodified",
    datenew = "datenew",
    albumduration = "albumduration"
}

export const AudioFieldsAlbumPropertiesMinimal = [
    AudioFieldsAlbum.title,
    AudioFieldsAlbum.artist,
    AudioFieldsAlbum.releasedate,
    AudioFieldsAlbum.art,
]

export const AudioFieldsAlbumPropertiesFull = [
    AudioFieldsAlbum.title,
    AudioFieldsAlbum.artist,
    AudioFieldsAlbum.artistid,
    AudioFieldsAlbum.releasedate,
    AudioFieldsAlbum.art,
    AudioFieldsAlbum.year,
    AudioFieldsAlbum.fanart,
    AudioFieldsAlbum.genre,
    AudioFieldsAlbum.totaldiscs,
]

export const enum AudioFieldSong {
    title = "title",
    artist = "artist",
    albumartist = "albumartist",
    genre = "genre",
    year = "year",
    rating = "rating",
    album = "album",
    track = "track",
    duration = "duration",
    comment = "comment",
    lyrics = "lyrics",
    musicbrainztrackid = "musicbrainztrackid",
    musicbrainzartistid = "musicbrainzartistid",
    musicbrainzalbumid = "musicbrainzalbumid",
    musicbrainzalbumartistid = "musicbrainzalbumartistid",
    playcount = "playcount",
    fanart = "fanart",
    thumbnail = "thumbnail",
    file = "file",
    albumid = "albumid",
    lastplayed = "lastplayed",
    disc = "disc",
    genreid = "genreid",
    artistid = "artistid",
    displayartist = "displayartist",
    albumartistid = "albumartistid",
    albumreleasetype = "albumreleasetype",
    dateadded = "dateadded",
    votes = "votes",
    userrating = "userrating",
    mood = "mood",
    contributors = "contributors",
    displaycomposer = "displaycomposer",
    displayconductor = "displayconductor",
    displayorchestra = "displayorchestra",
    displaylyricist = "displaylyricist",
    sortartist = "sortartist",
    art = "art",
    sourceid = "sourceid",
    disctitle = "disctitle",
    releasedate = "releasedate",
    originaldate = "originaldate",
    bpm = "bpm",
    samplerate = "samplerate",
    bitrate = "bitrate",
    channels = "channels",
    datemodified = "datemodified",
    datenew = "datenew"
}

export const AudioFieldsSongPropertiesMinimal = [
    AudioFieldSong.title,
    AudioFieldSong.artist,
    AudioFieldSong.releasedate,
    AudioFieldSong.art,
    AudioFieldSong.duration,
    AudioFieldSong.file,
    AudioFieldSong.track,
    AudioFieldSong.disc,
    AudioFieldSong.year,
]

export const AudioFieldsSongPropertiesFull = [
    AudioFieldSong.title,
    AudioFieldSong.artist,
    AudioFieldSong.albumartistid,
    AudioFieldSong.releasedate,
    AudioFieldSong.art,
    AudioFieldSong.duration,
    AudioFieldSong.year,
    AudioFieldSong.genre,
    AudioFieldSong.album,
    AudioFieldSong.albumid,
    AudioFieldSong.albumartist,
    AudioFieldSong.track,
]

export const enum AudioFieldArtist {
    instrument = "instrument",
    style = "style",
    mood = "mood",
    born = "born",
    formed = "formed",
    description = "description",
    genre = "genre",
    died = "died",
    disbanded = "disbanded",
    yearsactive = "yearsactive",
    musicbrainzartistid = "musicbrainzartistid",
    fanart = "fanart",
    thumbnail = "thumbnail",
    compilationartist = "compilationartist",
    dateadded = "dateadded",
    roles = "roles",
    songgenres = "songgenres",
    isalbumartist = "isalbumartist",
    sortname = "sortname",
    type = "type",
    gender = "gender",
    disambiguation = "disambiguation",
    art = "art",
    sourceid = "sourceid",
    datemodified = "datemodified",
    datenew = "datenew"
}

export const AudioFieldsArtistPropertiesMinimal = [
    AudioFieldArtist.art
]

export const AudioFieldsArtistPropertiesFull = [
    AudioFieldArtist.art,
    AudioFieldArtist.fanart,
    AudioFieldArtist.genre,
    AudioFieldArtist.born,
    AudioFieldArtist.songgenres,
    AudioFieldArtist.mood,
    AudioFieldArtist.formed,
    AudioFieldArtist.disbanded,
    AudioFieldArtist.description
]

