 
export enum ListFilterFieldsMovies {
    title = "title",
    originaltitle = "originaltitle",
    plot = "plot",
    plotoutline = "plotoutline",
    tagline = "tagline",
    votes = "votes",
    rating = "rating",
    userrating = "userrating",
    time = "time",
    writers = "writers",
    playcount = "playcount",
    lastplayed = "lastplayed",
    inprogress = "inprogress",
    genre = "genre",
    country = "country",
    year = "year",
    director = "director",
    actor = "actor",
    mpaarating = "mpaarating",
    top250 = "top250",
    studio = "studio",
    hastrailer = "hastrailer",
    filename = "filename",
    path = "path",
    set = "set",
    tag = "tag",
    dateadded = "dateadded",
    videoresolution = "videoresolution",
    audiochannels = "audiochannels",
    audiocount = "audiocount",
    subtitlecount = "subtitlecount",
    videocodec = "videocodec",
    audiocodec = "audiocodec",
    audiolanguage = "audiolanguage",
    subtitlelanguage = "subtitlelanguage",
    videoaspect = "videoaspect",
    playlist = "playlist",
    virtualfolder = "virtualfolder"
}

export enum ListFilterFieldsSong {
    genre = "genre",
    source = "source",
    album = "album",
    disctitle = "disctitle",
    artist = "artist",
    albumartist = "albumartist",
    title = "title",
    year = "year",
    originalyear = "originalyear",
    time = "time",
    tracknumber = "tracknumber",
    filename = "filename",
    path = "path",
    playcount = "playcount",
    lastplayed = "lastplayed",
    rating = "rating",
    userrating = "userrating",
    comment = "comment",
    moods = "moods",
    bpm = "bpm",
    samplerate = "samplerate",
    bitrate = "bitrate",
    channels = "channels",
    dateadded = "dateadded",
    datemodified = "datemodified",
    datenew = "datenew",
    playlist = "playlist",
    virtualfolder = "virtualfolder"
}

export enum ListFilterFieldsAlbums {
    genre = "genre",
    source = "source",
    album = "album",
    disctitle = "disctitle",
    totaldiscs = "totaldiscs",
    isboxset = "isboxset",
    artist = "artist",
    albumartist = "albumartist",
    year = "year",
    priginalyear = "originalyear",
    albumduration = "albumduration",
    review = "review",
    themes = "themes",
    moods = "moods",
    styles = "styles",
    compilation = "compilation",
    type = "type",
    label = "label",
    rating = "rating",
    userrating = "userrating",
    playcount = "playcount",
    lastplayed = "lastplayed",
    path = "path",
    albumstatus = "albumstatus",
    dateadded = "dateadded",
    datemodified = "datemodified",
    datenew = "datenew",
    playlist = "playlist",
    virtualfolder = "virtualfolder"
}

export enum ListFilterFiledArtist {
    artist = "artist",
    source = "source",
    genre = "genre",
    moods = "moods",
    styles = "styles",
    instruments = "instruments",
    biography = "biography",
    artisttype = "artisttype",
    gender = "gender",
    disambiguation = "disambiguation",
    born = "born",
    bandformed = "bandformed",
    disbanded = "disbanded",
    died = "died",
    role = "role",
    path = "path",
    dateadded = "dateadded",
    datemodifier = "datemodified",
    datenew = "datenew",
    playlist = "playlist",
    virtualfolder = "virtualfolder"
}